#!/usr/bin/env python3
"""Turn the census into a citable bibliography, a per-spectrum LaTeX appendix and a reference list.

Each catalogued spectrum gets an appendix row citing exactly one paper -- its most recent, the
one the `last` column reports -- so the census is cited rather than asserted without the
bibliography swelling to the size of the record. The .bib carries only those cited entries, with
title, journal reference and DOI as recorded on arXiv (refreshed by fetch_census_meta.py).

CENSUS_REFERENCES.md is the complete record, and the place the appendix points a reader who wants
it: every paper written out in full, numbered continuously and grouped under the spectrum each is
counted against. That is what makes the count in PUBLISHED_CENSUS.md checkable paper by paper.

Citation keys are `census:<arxiv-id>`, which cannot collide with the hand-written keys in the
consuming document's own refs.bib.

Reads  data/published_spectra.csv, data/census_papers.csv.
Writes results/tex/census_refs.bib, results/tex/census_appendix.tex,
       results/overviews/CENSUS_REFERENCES.md.
Pure standard library, no network.
"""
import csv, os, re, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def _p(*a): return os.path.join(ROOT, *a)

rows = list(csv.DictReader(open(_p("data", "published_spectra.csv"))))
papers = {r["arxiv"]: r for r in csv.DictReader(open(_p("data", "census_papers.csv")))}

ids = [a for r in rows for a in r["arxiv"].split()]
missing = sorted(set(ids) - set(papers))
if missing:
    raise SystemExit(f"no metadata for {missing}; run scripts/fetch_census_meta.py")


def rep_id(r):
    """The one paper cited for a spectrum: its most recent, i.e. what `last_year` reports."""
    return max(r["arxiv"].split(), key=lambda a: (int(papers[a]["year"]), a))


# One citation per spectrum, so the bibliography stays the length of the argument rather than
# of the record. The record itself is CENSUS_REFERENCES.md, which keeps all of them.
cited = {rep_id(r) for r in rows}

ENTITIES = {"&gt;": ">", "&lt;": "<", "&amp;": "&", "&quot;": '"', "&apos;": "'"}
SPECIALS = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_"}
# arXiv titles mix literal Greek with TeX. Map it to macros so the .bib needs no inputenc setup.
GREEK = {"γ": "gamma", "μ": "mu", "ν": "nu", "ρ": "rho", "τ": "tau",
         "φ": "varphi", "ψ": "psi", "ω": "omega", "Υ": "Upsilon"}


def tex(s):
    """arXiv title text -> LaTeX. Titles carry $...$ math already; escape only outside it."""
    for k, v in ENTITIES.items():
        s = s.replace(k, v)
    out = []
    for part in re.split(r"(\$[^$]*\$)", s):
        if part.startswith("$"):
            for ch, name in GREEK.items():                       # already in math mode
                part = part.replace(ch, f"\\{name} ")
        else:
            for k, v in SPECIALS.items():
                part = part.replace(k, v)
            for ch, name in GREEK.items():                       # needs its own math mode
                part = part.replace(ch, f"${{\\{name}}}$")
            # plain-text superscripts in untexed titles: "1 fb^-1", "tau^+ tau^-"
            part = re.sub(r"\^([+-]?\w*)", lambda m: f"$^{{{m.group(1)}}}$", part)
        out.append(part)
    s = "".join(out)
    if any(ord(c) > 126 for c in s):
        raise SystemExit(f"unmapped non-ASCII in {s!r}; extend GREEK")
    outside = "".join(p for p in re.split(r"(\$[^$]*\$)", s) if not p.startswith("$"))
    if set("^~") & set(outside) or outside.count("$"):
        raise SystemExit(f"unescaped LaTeX special outside math in {s!r}")
    return s


# ------------------------------------------------------------------ the .bib
with open(_p("results", "tex", "census_refs.bib"), "w") as f:
    f.write("% Generated by scripts/export_census_bib.py from data/census_papers.csv.\n"
            "% The most recent paper of each spectrum in the publication census -- one per\n"
            "% spectrum, which is what the appendix cites. The full record of every paper is\n"
            "% results/overviews/CENSUS_REFERENCES.md.\n"
            "% Do not edit: regenerate instead.\n\n")
    for aid in sorted(cited, key=lambda a: (papers[a]["year"], a)):
        p = papers[aid]
        f.write(f"@article{{census:{aid},\n")
        f.write("  author        = {{ATLAS Collaboration}},\n")
        f.write(f"  title         = {{{{{tex(p['title'])}}}}},\n")
        if p["journal"]:
            f.write(f"  journal       = {{{tex(p['journal'])}}},\n")
        f.write(f"  year          = {{{p['year']}}},\n")
        if p["doi"]:
            f.write(f"  doi           = {{{p['doi']}}},\n")
        f.write(f"  eprint        = {{{aid}}},\n")
        f.write("  archivePrefix = {arXiv},\n")
        # `note` is what the numeric style prints; the consuming document uses unsrt because
        # BibTeX's author-year suffix runs out of letters past 26 same-author, same-year entries,
        # and four years here exceed that.
        f.write(f"  note          = {{arXiv:{aid}}},\n}}\n\n")

# ------------------------------------------------------------------ the appendix
by_fam = collections.defaultdict(list)
for r in rows:
    by_fam[r["family"]].append(r)

TEXNAME = {"&": r"\&"}
def fam_tex(s):
    for k, v in TEXNAME.items():
        s = s.replace(k, v)
    return s

with open(_p("results", "tex", "census_appendix.tex"), "w") as f:
    f.write("% Generated by scripts/export_census_bib.py. Do not edit: regenerate instead.\n")
    f.write("\\section{The publication census, spectrum by spectrum}\n")
    f.write("\\label{app:census}\n\n")
    f.write(f"""Every entry of the census of Section~\\ref{{sec:census}}, grouped by final state. The
{len(rows)} entries below carry {len(set(ids))} distinct papers between
{min(p['year'] for p in papers.values())} and {max(p['year'] for p in papers.values())}; \\emph{{n}}
is how many scan that spectrum and \\emph{{last}} is the year of the most recent, which is what the
recency classification in Table~\\ref{{tab:census}} is built from.

Only that most recent paper is cited, one per spectrum, so the bibliography stays the length of the
argument rather than of the record. The record itself lives with the code, as
\\texttt{{CENSUS\\_REFERENCES.md}} under \\texttt{{results/overviews/}}, and lists all
{len(set(ids))} with title, journal reference and DOI, grouped under the spectrum each is counted
against. Assembled from the collaboration's publication record and curated by hand, so it is
complete to the best of our knowledge rather than machine-verifiable. Scope matches the budget's, so
hadron-spectroscopy measurements are excluded even where they are bump hunts in a mass spectrum.

\\begin{{longtable}}{{@{{}}>{{\\raggedright\\arraybackslash}}p{{0.25\\textwidth}}>{{\\raggedright\\arraybackslash}}p{{0.175\\textwidth}}rr>{{\\raggedright\\arraybackslash}}p{{0.25\\textwidth}}@{{}}}}
\\toprule
spectrum & observable & n & last & most recent paper \\\\
\\midrule
\\endfirsthead
\\toprule
spectrum & observable & n & last & most recent paper \\\\
\\midrule
\\endhead
\\bottomrule
\\endlastfoot
""")
    for fam in sorted(by_fam):
        f.write(f"\\multicolumn{{5}}{{@{{}}l}}{{\\textbf{{{fam_tex(fam)}}}}} \\\\[1pt]\n")
        for r in sorted(by_fam[fam], key=lambda r: r["spectrum"]):
            f.write(f"\\quad {fam_tex(tex(r['spectrum']))} & \\texttt{{{tex(r['observable'])}}} & "
                    f"{len(r['arxiv'].split())} & {r['last_year']} & "
                    f"\\cite{{census:{rep_id(r)}}} \\\\\n")
        f.write("\\addlinespace[3pt]\n")
    f.write("\\end{longtable}\n")

# ------------------------------------------------------------------ the reference list
# arXiv titles are half TeX, half literal Unicode. The overviews are ASCII-ish like their
# neighbours, so unwrap the macros that actually occur rather than rendering math.
MACROS = {r"\rightarrow": "->", r"\mathrm": "", r"\mathbf": "", r"\text": "", r"\prime": "'",
          r"\sqrt": "sqrt", r"\ell": "l", r"\bar": "bar", r"\pm": "+-", r"\mp": "-+", r"\to": "->",
          r"\,": " "}
LETTERS = {"γ": "gamma", "μ": "mu", "ν": "nu", "ρ": "rho", "τ": "tau", "φ": "phi",
           "ψ": "psi", "ω": "omega", "Υ": "Upsilon"}


def plain(s):
    """arXiv title text -> readable ASCII. Guards, so an unmapped macro fails the build."""
    s = s.replace("&gt;", ">").replace("&lt;", "<").replace("&amp;", "&")
    s = re.sub(r"\\sqrt\{([^{}]*)\}", r"sqrt(\1)", s)
    s = re.sub(r"\\bar\{([^{}]*)\}", r"\1bar", s)
    s = re.sub(r"\\bar\s*(\w)", r"\1bar", s)                 # \bar\nu -> nubar, not barnu
    for m in sorted(MACROS, key=len, reverse=True):          # \rightarrow before \to, \text before \to
        s = s.replace(m, MACROS[m])
    if "\\" in s:
        raise SystemExit(f"unmapped TeX macro in {s!r}; extend MACROS")
    s = s.replace("$", "")
    s = re.sub(r"\^\{([^{}]*)\}", r"^\1", s)
    s = s.replace("{", "").replace("}", "")                  # safe: no macros left to strip
    s = s.replace("^'", "'")                                 # l^' -> l', the primed lepton
    for ch, name in LETTERS.items():
        s = s.replace(ch, name)
    if any(ord(c) > 126 for c in s):
        raise SystemExit(f"unmapped non-ASCII in {s!r}; extend LETTERS")
    return re.sub(r"\s+", " ", s).strip()


def md(s):
    return s.replace("*", r"\*").replace("_", r"\_")


years = [p["year"] for p in papers.values()]
nj = sum(1 for a in set(ids) if papers[a]["journal"])
with open(_p("results", "overviews", "CENSUS_REFERENCES.md"), "w") as f:
    f.write(f"""# The census, reference by reference

The {len(set(ids))} ATLAS papers behind the census of `PUBLISHED_CENSUS.md`, written out in full.
Each is listed under the one spectrum it is counted against, so the {len(rows)} headings below carry
{len(set(ids))} references between them and the numbering runs to {len(set(ids))} exactly.

Where the count comes from: the census records, per catalogued spectrum, every published ATLAS
search that scans it, and each paper is attributed to a single spectrum -- the one whose mass axis
it is a bump hunt in. So {len(set(ids))} is the sum of the per-spectrum paper counts, with no
double counting and no paper appearing twice. Scope matches the budget's: bump hunts for new
states, which leaves out hadron-spectroscopy measurements even where they are bumps in a mass
spectrum.

**This is a different base from the trials budget and must not be added to it.** The budget counts
46 canonical mass axes that public BSM models motivate; this counts what has been published, which
separates analyses that share an axis. See `docs/METHOD_NOTES.md`.

Titles, journal references and DOIs are as recorded on arXiv ({nj} of {len(set(ids))} have a journal
reference so far). TeX in the titles is unwrapped into plain text, so `sqrt(s)` reads for the
centre-of-mass energy and Greek letters are spelled out.

Generated by `scripts/export_census_bib.py` from `data/published_spectra.csv` and
`data/census_papers.csv`; the same content is in `results/tex/census_refs.bib` as BibTeX. Do not
edit by hand: regenerate instead.

Papers span {min(years)}-{max(years)}.

""")
    n = 0
    for fam in sorted(by_fam):
        f.write(f"## {fam}\n\n")
        for r in sorted(by_fam[fam], key=lambda r: r["spectrum"]):
            aids = r["arxiv"].split()
            f.write(f"### {md(plain(r['spectrum']))}: `{r['observable']}`\n\n")
            f.write(f"{len(aids)} paper{'s' if len(aids) > 1 else ''}, "
                    f"{r['first_year']}-{r['last_year']} ({r['status']}).\n\n")
            for aid in sorted(aids, key=lambda a: (papers[a]["year"], a)):
                p = papers[aid]
                n += 1
                bits = [f"ATLAS Collaboration, {md(plain(p['title']))}"]
                if p["journal"]:
                    bits.append(md(plain(p["journal"])))
                # angle-bracketed destinations: JHEP DOIs contain parentheses
                bits.append(f"[arXiv:{aid}](<https://arxiv.org/abs/{aid}>)")
                if p["doi"]:
                    bits.append(f"[doi:{p['doi']}](<https://doi.org/{p['doi']}>)")
                f.write(f"{n}. " + ", ".join(bits) + f", {p['year']}.\n")
            f.write("\n")
    if n != len(set(ids)):
        raise SystemExit(f"listed {n} references but the census has {len(set(ids))}")

print(f"wrote results/tex/census_refs.bib ({len(cited)} entries cited, "
      f"one per spectrum, out of {len(set(ids))} papers)")
print(f"wrote results/tex/census_appendix.tex ({len(rows)} spectra, {len(by_fam)} families)")
print(f"wrote results/overviews/CENSUS_REFERENCES.md ({n} references)")
