#!/usr/bin/env python3
"""Turn the census into a citable bibliography plus a per-spectrum LaTeX appendix.

Every paper behind the census gets a real BibTeX entry (title, journal reference and DOI as
recorded on arXiv, refreshed by fetch_census_meta.py), and every catalogued spectrum gets an
appendix row citing all of its papers. That way the census is cited rather than asserted, and the
count in PUBLISHED_CENSUS.md can be checked paper by paper.

Citation keys are `census:<arxiv-id>`, which cannot collide with the hand-written keys in the
consuming document's own refs.bib.

Reads  data/published_spectra.csv, data/census_papers.csv.
Writes results/tex/census_refs.bib, results/tex/census_appendix.tex.
Pure standard library, no network.
"""
import csv, os, re, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def _p(*a): return os.path.join(ROOT, *a)

rows = list(csv.DictReader(open(_p("data", "published_spectra.csv"))))
papers = {r["arxiv"]: r for r in csv.DictReader(open(_p("data", "census_papers.csv")))}

ids = [a for r in rows for a in r["arxiv"].split()]
missing = sorted(set(ids) - set(papers))
if missing:
    raise SystemExit(f"no metadata for {missing}; run scripts/fetch_census_meta.py")

ENTITIES = {"&gt;": ">", "&lt;": "<", "&amp;": "&", "&quot;": '"', "&apos;": "'"}
SPECIALS = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_"}
# arXiv titles mix literal Greek with TeX. Map it to macros so the .bib needs no inputenc setup.
GREEK = {"γ": "gamma", "μ": "mu", "ν": "nu", "ρ": "rho", "τ": "tau",
         "φ": "varphi", "ψ": "psi", "ω": "omega", "Υ": "Upsilon"}


def tex(s):
    """arXiv title text -> LaTeX. Titles carry $...$ math already; escape only outside it."""
    for k, v in ENTITIES.items():
        s = s.replace(k, v)
    out = []
    for part in re.split(r"(\$[^$]*\$)", s):
        if part.startswith("$"):
            for ch, name in GREEK.items():                       # already in math mode
                part = part.replace(ch, f"\\{name} ")
        else:
            for k, v in SPECIALS.items():
                part = part.replace(k, v)
            for ch, name in GREEK.items():                       # needs its own math mode
                part = part.replace(ch, f"${{\\{name}}}$")
            # plain-text superscripts in untexed titles: "1 fb^-1", "tau^+ tau^-"
            part = re.sub(r"\^([+-]?\w*)", lambda m: f"$^{{{m.group(1)}}}$", part)
        out.append(part)
    s = "".join(out)
    if any(ord(c) > 126 for c in s):
        raise SystemExit(f"unmapped non-ASCII in {s!r}; extend GREEK")
    outside = "".join(p for p in re.split(r"(\$[^$]*\$)", s) if not p.startswith("$"))
    if set("^~") & set(outside) or outside.count("$"):
        raise SystemExit(f"unescaped LaTeX special outside math in {s!r}")
    return s


# ------------------------------------------------------------------ the .bib
with open(_p("results", "tex", "census_refs.bib"), "w") as f:
    f.write("% Generated by scripts/export_census_bib.py from data/census_papers.csv.\n"
            "% Every ATLAS resonance-search paper counted in the publication census.\n"
            "% Do not edit: regenerate instead.\n\n")
    for aid in sorted(set(ids), key=lambda a: (papers[a]["year"], a)):
        p = papers[aid]
        f.write(f"@article{{census:{aid},\n")
        f.write("  author        = {{ATLAS Collaboration}},\n")
        f.write(f"  title         = {{{{{tex(p['title'])}}}}},\n")
        if p["journal"]:
            f.write(f"  journal       = {{{tex(p['journal'])}}},\n")
        f.write(f"  year          = {{{p['year']}}},\n")
        if p["doi"]:
            f.write(f"  doi           = {{{p['doi']}}},\n")
        f.write(f"  eprint        = {{{aid}}},\n")
        f.write("  archivePrefix = {arXiv},\n")
        # `note` is what the numeric style prints; the consuming document uses unsrt because
        # BibTeX's author-year suffix runs out of letters past 26 same-author, same-year entries,
        # and four years here exceed that.
        f.write(f"  note          = {{arXiv:{aid}}},\n}}\n\n")

# ------------------------------------------------------------------ the appendix
by_fam = collections.defaultdict(list)
for r in rows:
    by_fam[r["family"]].append(r)

TEXNAME = {"&": r"\&"}
def fam_tex(s):
    for k, v in TEXNAME.items():
        s = s.replace(k, v)
    return s

with open(_p("results", "tex", "census_appendix.tex"), "w") as f:
    f.write("% Generated by scripts/export_census_bib.py. Do not edit: regenerate instead.\n")
    f.write("\\section{The publication census, spectrum by spectrum}\n")
    f.write("\\label{app:census}\n\n")
    f.write(f"""Every entry of the census of Section~\\ref{{sec:census}}, grouped by final state, with the ATLAS
papers that scan it. The {len(rows)} entries below carry {len(set(ids))} distinct papers between
{min(p['year'] for p in papers.values())} and {max(p['year'] for p in papers.values())}; the
\\emph{{last}} column is the year of the most recent one, which is what the recency classification in
Table~\\ref{{tab:census}} is built from. Assembled from the collaboration's publication record and
curated by hand, so it is complete to the best of our knowledge rather than machine-verifiable.
Scope matches the budget's, so hadron-spectroscopy measurements are excluded even where they are
bump hunts in a mass spectrum.

\\begin{{longtable}}{{@{{}}>{{\\raggedright\\arraybackslash}}p{{0.27\\textwidth}}>{{\\raggedright\\arraybackslash}}p{{0.17\\textwidth}}r>{{\\raggedright\\arraybackslash}}p{{0.39\\textwidth}}@{{}}}}
\\toprule
spectrum & observable & last & papers \\\\
\\midrule
\\endfirsthead
\\toprule
spectrum & observable & last & papers \\\\
\\midrule
\\endhead
\\bottomrule
\\endlastfoot
""")
    for fam in sorted(by_fam):
        f.write(f"\\multicolumn{{4}}{{@{{}}l}}{{\\textbf{{{fam_tex(fam)}}}}} \\\\[1pt]\n")
        for r in sorted(by_fam[fam], key=lambda r: r["spectrum"]):
            cites = ",".join(f"census:{a}" for a in r["arxiv"].split())
            f.write(f"\\quad {fam_tex(tex(r['spectrum']))} & \\texttt{{{tex(r['observable'])}}} & "
                    f"{r['last_year']} & \\cite{{{cites}}} \\\\\n")
        f.write("\\addlinespace[3pt]\n")
    f.write("\\end{longtable}\n")

print(f"wrote results/tex/census_refs.bib ({len(set(ids))} entries)")
print(f"wrote results/tex/census_appendix.tex ({len(rows)} spectra, {len(by_fam)} families)")
