#!/usr/bin/env python3
import collections, csv, math, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
from bump_observables import (canon, CANON_ORDER, ns_scan, n_s, res,
                              z_local_for_global5 as z5)
from public_obs_map import PUBLIC_OBS
import yield_model as YM

def _p(*a): return os.path.join(ROOT, *a)

OBJ = [("e", "$e$"), ("mu", r"$\mu$"), ("tau", r"$\tau$"), ("j", "$q/g$"), ("b", "$b$"),
       ("t", "$t$"), ("ga", r"$\gamma$"), ("V", "$Z/W$"), ("H", "$H$")]
KEYS = [k for k, _ in OBJ]

PAIR = {
    "m(gammagamma)": ("ga", "ga"), "m(ee)": ("e", "e"), "m(ee) (Zd)": ("e", "e"),
    "m(ee) SS": ("e", "e"), "m(mumu)": ("mu", "mu"), "m(mumu) (Zd)": ("mu", "mu"),
    "m(mumu) SS": ("mu", "mu"), "m(tautau)": ("tau", "tau"),
    "m(emu) LFV": ("e", "mu"), "m(emu) SS": ("e", "mu"),
    "m(etau) LFV": ("e", "tau"), "m(mutau) LFV": ("mu", "tau"),
    "m(ej)": ("e", "j"), "m(muj)": ("mu", "j"), "m(tauj)": ("tau", "j"),
    "m(eb)": ("e", "b"), "m(mub)": ("mu", "b"), "m(taub)": ("tau", "b"),
    "m(egamma)": ("e", "ga"), "m(mugamma)": ("mu", "ga"), "m(jgamma)": ("j", "ga"),
    "m(Vgamma)": ("V", "ga"),
    "m(jj)": ("j", "j"), "m(cb) dijet": ("b", "j"), "m(bj)": ("b", "j"), "m(bb)": ("b", "b"),
    "m(tt)": ("t", "t"), "m(tb)": ("t", "b"), "m(tt)/m(jj)": ("t", "t"),
    "m(VV)": ("V", "V"), "m(Vh)": ("V", "H"), "m(HH)": ("H", "H"), "m(Ht)": ("H", "t"),
    "m(Wb)": ("V", "b"), "m(tW)": ("t", "V"), "m(ttZ)/m(Zt)": ("t", "V"),
    "m(eZ)": ("e", "V"), "m(muZ)": ("mu", "V"),
    "multilepton": None, "m(3j)": None, "m(multi)": None,
    "m(eejj)": None, "m(mumujj)": None,
    "mT(ev)": None, "mT(muv)": None, "mT(taunu)": None,
}

SYM = {"e": "m(ee)", "mu": "m(mumu)", "tau": "m(tautau)", "j": "m(jj)", "b": "m(bb)",
       "t": "m(tt)", "ga": "m(gammagamma)", "V": "m(VV)", "H": "m(HH)"}
GAP_WINDOW = (100.0, 5000.0)

by_obs = collections.defaultdict(set)
for m, obss in PUBLIC_OBS.items():
    for o in obss:
        by_obs[canon(o)].add(m)
order = [o for o in CANON_ORDER if o == canon(o) and o in by_obs]
order += [o for o in sorted(by_obs) if o not in order]

missing = [o for o in order if o not in PAIR]
if missing:
    raise SystemExit(f"no object pair classified for {missing}; extend PAIR")
stale = [o for o in PAIR if o not in order]
if stale:
    raise SystemExit(f"PAIR names a spectrum that is not in the catalogue: {stale}")

def cell(a, b):
    return tuple(sorted((a, b), key=KEYS.index))

spent = collections.defaultdict(float)
axes = collections.defaultdict(list)
for o in order:
    if PAIR[o] is None:
        continue
    c = cell(*PAIR[o])
    spent[c] += ns_scan(o)
    axes[c].append(o)

sigma = {k: 2.0 * res(SYM[k]) for k in KEYS}
YKEY = {"e": "e", "mu": "m", "tau": "T", "j": "j", "b": "b", "t": "t", "ga": "g", "V": "V", "H": "H"}

def gap_price(a, b):
    r = 0.5 * math.sqrt((sigma[a] ** 2 + sigma[b] ** 2) / 2.0)
    w = YM.weight(YKEY[a] + YKEY[b])
    _hi, ns, _ev, fits = YM.gate(*GAP_WINDOW, r, w)
    return ns if fits else 0.0

cells = [cell(a, b) for i, a in enumerate(KEYS) for b in KEYS[i:]]
gaps = [c for c in cells if c not in spent]
thin = [c for c in gaps if gap_price(*c) == 0.0]
gap_total = sum(gap_price(*c) for c in gaps)
n_now = sum(ns_scan(o) for o in order)

label = dict(OBJ)
with open(_p("results", "tex", "two_body_matrix.tex"), "w") as f:
    f.write("% Generated by scripts/two_body_matrix.py. Do not edit: regenerate instead.\n")
    f.write("\\begin{tabular}{l" + "r" * len(KEYS) + "}\n\\toprule\n")
    f.write(" & " + " & ".join(label[k] for k in KEYS) + " \\\\\n\\midrule\n")
    for i, a in enumerate(KEYS):
        row = [label[a]]
        row += [""] * i
        for b in KEYS[i:]:
            c = cell(a, b)
            if c in spent:
                row.append(f"{spent[c]:.0f}")
            else:
                p = gap_price(*c)
                row.append(f"\\textit{{({p:.0f})}}" if p else "\\textit{(--)}")
        f.write(" & ".join(row) + " \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n")

with open(_p("results", "tables", "two_body_matrix.csv"), "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["object_1", "object_2", "status", "ns", "n_axes", "axes"])
    for c in cells:
        if c in spent:
            w.writerow([c[0], c[1], "scanned", f"{spent[c]:.1f}", len(axes[c]),
                        "; ".join(sorted(axes[c]))])
        else:
            p = gap_price(*c)
            w.writerow([c[0], c[1], "gap" if p else "gap, too thin to fit", f"{p:.1f}", 0, ""])

print(f"wrote results/tex/two_body_matrix.tex, results/tables/two_body_matrix.csv")
print(f"{len(cells)} pairs: {len(spent)} scanned, {len(gaps)} with no axis in the catalogue, "
      f"of which {len(thin)} cannot hold a fittable histogram")
print(f"gaps: {sorted('-'.join(c) for c in gaps)}")
print(f"too thin: {sorted('-'.join(c) for c in thin)}")
print(f"closing every gap: N {n_now:,.0f} -> {n_now + gap_total:,.0f} "
      f"(+{gap_total:,.0f}), Z {z5(n_now):.2f} -> {z5(n_now + gap_total):.2f}")
