import collections
import re

from .. import io, paths
from ..core.bump_observables import SCAN
from ..registry import stage

ENTITIES = {"&gt;": ">", "&lt;": "<", "&amp;": "&", "&quot;": '"', "&apos;": "'"}
SPECIALS = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_"}
GREEK = {"γ": "gamma", "μ": "mu", "ν": "nu", "π": "pi", "ρ": "rho",
         "τ": "tau", "φ": "varphi", "ψ": "psi", "ω": "omega",
         "Υ": "Upsilon"}
MACROS = {r"\rightarrow": "->", r"\mathrm": "", r"\mathbf": "", r"\text": "", r"\prime": "'",
          r"\sqrt": "sqrt", r"\ell": "l", r"\bar": "bar", r"\pm": "+-", r"\mp": "-+",
          r"\to": "->", r"\rm": "", r"\,": " "}
LETTERS = {"γ": "gamma", "μ": "mu", "ν": "nu", "π": "pi", "ρ": "rho",
           "τ": "tau", "φ": "phi", "ψ": "psi", "ω": "omega",
           "Υ": "Upsilon"}
TEXNAME = {"&": r"\&"}


@stage(
    name="census-bib",
    group="census",
    summary="the census as BibTeX, a LaTeX appendix and the full reference list",
    outputs=["tex/census_refs.bib", "tex/census_appendix.tex",
             "overviews/CENSUS_REFERENCES.md"],
    inputs=["data/published_spectra.csv", "data/census_papers.csv"],
)
def main(options=None):
    rows = io.read_rows(paths.data("published_spectra.csv"))
    papers = {r["arxiv"]: r for r in io.read_rows(paths.data("census_papers.csv"))}
    n_axes = len(SCAN)

    ids = [a for r in rows for a in r["arxiv"].split()]
    missing = sorted(set(ids) - set(papers))
    if missing:
        raise SystemExit(f"no metadata for {missing}; run `search-budget run fetch-census-meta`")


    def rep_id(r):
        return max(r["arxiv"].split(), key=lambda a: (int(papers[a]["year"]), a))


    cited = {rep_id(r) for r in rows}

    def tex(s):
        for k, v in ENTITIES.items():
            s = s.replace(k, v)
        out = []
        for part in re.split(r"(\$[^$]*\$)", s):
            if part.startswith("$"):
                for ch, name in GREEK.items():
                    part = part.replace(ch, f"\\{name} ")
            else:
                for k, v in SPECIALS.items():
                    part = part.replace(k, v)
                for ch, name in GREEK.items():
                    part = part.replace(ch, f"${{\\{name}}}$")
                part = re.sub(r"\^([+-]?\w*)", lambda m: f"$^{{{m.group(1)}}}$", part)
            out.append(part)
        s = "".join(out)
        if any(ord(c) > 126 for c in s):
            raise SystemExit(f"unmapped non-ASCII in {s!r}; extend GREEK")
        outside = "".join(p for p in re.split(r"(\$[^$]*\$)", s) if not p.startswith("$"))
        if set("^~") & set(outside) or outside.count("$"):
            raise SystemExit(f"unescaped LaTeX special outside math in {s!r}")
        return s


    with open(io.ensure(paths.tex("census_refs.bib")), "w") as f:
        f.write("% Generated by searchbudget/stages/census_bib.py from data/census_papers.csv.\n"
                "% The most recent paper of each spectrum in the publication census -- one per\n"
                "% spectrum, which is what the appendix cites. The full record of every paper is\n"
                "% results/overviews/CENSUS_REFERENCES.md.\n"
                "% Do not edit: regenerate instead.\n\n")
        for aid in sorted(cited, key=lambda a: (papers[a]["year"], a)):
            p = papers[aid]
            f.write(f"@article{{census:{aid},\n")
            f.write("  author        = {{ATLAS Collaboration}},\n")
            f.write(f"  title         = {{{{{tex(p['title'])}}}}},\n")
            if p["journal"]:
                f.write(f"  journal       = {{{tex(p['journal'])}}},\n")
            f.write(f"  year          = {{{p['year']}}},\n")
            if p["doi"]:
                f.write(f"  doi           = {{{p['doi']}}},\n")
            f.write(f"  eprint        = {{{aid}}},\n")
            f.write("  archivePrefix = {arXiv},\n")
            f.write(f"  note          = {{arXiv:{aid}}},\n}}\n\n")

    by_fam = collections.defaultdict(list)
    for r in rows:
        by_fam[r["family"]].append(r)

    def fam_tex(s):
        for k, v in TEXNAME.items():
            s = s.replace(k, v)
        return s

    with open(io.ensure(paths.tex("census_appendix.tex")), "w") as f:
        f.write("% Generated by searchbudget/stages/census_bib.py. Do not edit: regenerate instead.\n")
        f.write("\\section{The Publication Census, Spectrum by Spectrum}\n")
        f.write("\\label{app:census}\n\n")
        f.write(f"""Every entry of the census of Section~\\ref{{sec:census}}, grouped by final state. The
{len(rows)} entries below carry {len(set(ids))} distinct papers between
{min(p['year'] for p in papers.values())} and {max(p['year'] for p in papers.values())}; \\emph{{n}}
is how many scan that spectrum and \\emph{{last}} is the year of the most recent, which is what the
recency classification in Table~\\ref{{tab:census}} is built from.

Only that most recent paper is cited, one per spectrum, so the bibliography stays the length of the
argument rather than of the record. The record itself lives with the code
(\\url{{https://github.com/rodem-hep/search-budget}}), as \\texttt{{CENSUS\\_REFERENCES.md}} under
\\texttt{{results/overviews/}}, and lists all
{len(set(ids))} with title, journal reference and DOI, grouped under the spectrum each is counted
against. Assembled from the collaboration's publication record and curated by hand, so it is
complete to the best of our knowledge rather than machine-verifiable. Scope matches the budget's, so
hadron-spectroscopy measurements are excluded even where they are bump hunts in a mass spectrum.

\\begin{{longtable}}{{@{{}}>{{\\raggedright\\arraybackslash}}p{{0.25\\textwidth}}>{{\\raggedright\\arraybackslash}}p{{0.175\\textwidth}}rr>{{\\raggedright\\arraybackslash}}p{{0.25\\textwidth}}@{{}}}}
\\toprule
spectrum & observable & n & last & most recent paper \\\\
\\midrule
\\endfirsthead
\\toprule
spectrum & observable & n & last & most recent paper \\\\
\\midrule
\\endhead
\\bottomrule
\\endlastfoot
""")
        for fam in sorted(by_fam):
            f.write(f"\\multicolumn{{5}}{{@{{}}l}}{{\\textbf{{{fam_tex(fam)}}}}} \\\\[1pt]\n")
            for r in sorted(by_fam[fam], key=lambda r: r["spectrum"]):
                f.write(f"\\quad {fam_tex(tex(r['spectrum']))} & \\texttt{{{tex(r['observable'])}}} & "
                        f"{len(r['arxiv'].split())} & {r['last_year']} & "
                        f"\\cite{{census:{rep_id(r)}}} \\\\\n")
            f.write("\\addlinespace[3pt]\n")
        f.write("\\end{longtable}\n")

    def plain(s):
        s = s.replace("&gt;", ">").replace("&lt;", "<").replace("&amp;", "&")
        s = re.sub(r"\\sqrt\{([^{}]*)\}", r"sqrt(\1)", s)
        s = re.sub(r"\\bar\{([^{}]*)\}", r"\1bar", s)
        s = re.sub(r"\\bar\s*(\w)", r"\1bar", s)
        for m in sorted(MACROS, key=len, reverse=True):
            s = s.replace(m, MACROS[m])
        if "\\" in s:
            raise SystemExit(f"unmapped TeX macro in {s!r}; extend MACROS")
        s = s.replace("$", "")
        s = re.sub(r"\^\{([^{}]*)\}", r"^\1", s)
        s = s.replace("{", "").replace("}", "")
        s = s.replace("^'", "'")
        for ch, name in LETTERS.items():
            s = s.replace(ch, name)
        if any(ord(c) > 126 for c in s):
            raise SystemExit(f"unmapped non-ASCII in {s!r}; extend LETTERS")
        return re.sub(r"\s+", " ", s).strip()


    def md(s):
        return s.replace("*", r"\*").replace("_", r"\_")


    years = [p["year"] for p in papers.values()]
    nj = sum(1 for a in set(ids) if papers[a]["journal"])
    with open(io.ensure(paths.overview("CENSUS_REFERENCES.md")), "w") as f:
        f.write(f"""# The census, reference by reference

The {len(set(ids))} ATLAS papers behind the census of `PUBLISHED_CENSUS.md`, written out in full.
Each is listed under the one spectrum it is counted against, so the {len(rows)} headings below carry
{len(set(ids))} references between them and the numbering runs to {len(set(ids))} exactly.

Where the count comes from: the census records, per catalogued spectrum, every published ATLAS
search that scans it, and each paper is attributed to a single spectrum -- the one whose mass axis
it is a bump hunt in. So {len(set(ids))} is the sum of the per-spectrum paper counts, with no
double counting and no paper appearing twice. Scope matches the budget's: bump hunts for new
states, which leaves out hadron-spectroscopy measurements even where they are bumps in a mass
spectrum.

**This is a different base from the trials budget and must not be added to it.** The budget counts
{n_axes} canonical mass axes that public BSM models motivate; this counts what has been published, which
separates analyses that share an axis. See `docs/METHOD_NOTES.md`.

Titles, journal references and DOIs are as recorded on arXiv ({nj} of {len(set(ids))} have a journal
reference so far). TeX in the titles is unwrapped into plain text, so `sqrt(s)` reads for the
centre-of-mass energy and Greek letters are spelled out.

Generated by `searchbudget/stages/census_bib.py` from `data/published_spectra.csv` and
`data/census_papers.csv`; the same content is in `results/tex/census_refs.bib` as BibTeX. Do not
edit by hand: regenerate instead.

Papers span {min(years)}-{max(years)}.

""")
        n = 0
        for fam in sorted(by_fam):
            f.write(f"## {fam}\n\n")
            for r in sorted(by_fam[fam], key=lambda r: r["spectrum"]):
                aids = r["arxiv"].split()
                f.write(f"### {md(plain(r['spectrum']))}: `{r['observable']}`\n\n")
                f.write(f"{len(aids)} paper{'s' if len(aids) > 1 else ''}, "
                        f"{r['first_year']}-{r['last_year']} ({r['status']}).\n\n")
                for aid in sorted(aids, key=lambda a: (papers[a]["year"], a)):
                    p = papers[aid]
                    n += 1
                    bits = [f"ATLAS Collaboration, {md(plain(p['title']))}"]
                    if p["journal"]:
                        bits.append(md(plain(p["journal"])))
                    bits.append(f"[arXiv:{aid}](<https://arxiv.org/abs/{aid}>)")
                    if p["doi"]:
                        bits.append(f"[doi:{p['doi']}](<https://doi.org/{p['doi']}>)")
                    f.write(f"{n}. " + ", ".join(bits) + f", {p['year']}.\n")
                f.write("\n")
        if n != len(set(ids)):
            raise SystemExit(f"listed {n} references but the census has {len(set(ids))}")

    print(f"wrote results/tex/census_refs.bib ({len(cited)} entries cited, "
          f"one per spectrum, out of {len(set(ids))} papers)")
    print(f"wrote results/tex/census_appendix.tex ({len(rows)} spectra, {len(by_fam)} families)")
    print(f"wrote results/overviews/CENSUS_REFERENCES.md ({n} references)")
