import collections
import math

from .. import io, paths
from ..core import yield_model as YM
from ..core.bump_observables import ns_scan, res, z_local_for_global5 as z5
from ..core.catalogue import canonical_order, models_by_spectrum
from ..registry import stage

OBJ = [("e", "$e$"), ("mu", r"$\mu$"), ("tau", r"$\tau$"), ("j", "$q/g$"), ("b", "$b$"),
       ("t", "$t$"), ("ga", r"$\gamma$"), ("V", "$Z/W$"), ("H", "$H$")]
KEYS = [k for k, _ in OBJ]

PAIR = {
    "m(gammagamma)": ("ga", "ga"), "m(ee)": ("e", "e"), "m(ee) (Zd)": ("e", "e"),
    "m(ee) SS": ("e", "e"), "m(mumu)": ("mu", "mu"), "m(mumu) (Zd)": ("mu", "mu"),
    "m(mumu) SS": ("mu", "mu"), "m(tautau)": ("tau", "tau"),
    "m(emu) LFV": ("e", "mu"), "m(emu) SS": ("e", "mu"),
    "m(etau) LFV": ("e", "tau"), "m(mutau) LFV": ("mu", "tau"),
    "m(ej)": ("e", "j"), "m(muj)": ("mu", "j"), "m(tauj)": ("tau", "j"),
    "m(eb)": ("e", "b"), "m(mub)": ("mu", "b"), "m(taub)": ("tau", "b"),
    "m(egamma)": ("e", "ga"), "m(mugamma)": ("mu", "ga"), "m(jgamma)": ("j", "ga"),
    "m(Vgamma)": ("V", "ga"),
    "m(jj)": ("j", "j"), "m(cb) dijet": ("b", "j"), "m(bj)": ("b", "j"), "m(bb)": ("b", "b"),
    "m(tt)": ("t", "t"), "m(tb)": ("t", "b"), "m(tt)/m(jj)": ("t", "t"),
    "m(VV)": ("V", "V"), "m(Vh)": ("V", "H"), "m(HH)": ("H", "H"), "m(Ht)": ("H", "t"),
    "m(Wb)": ("V", "b"), "m(tW)": ("t", "V"), "m(ttZ)/m(Zt)": ("t", "V"),
    "m(eZ)": ("e", "V"), "m(muZ)": ("mu", "V"),
    "m(bgamma)": ("b", "ga"), "m(tgamma)": ("t", "ga"), "m(taugamma)": ("tau", "ga"),
    "m(bZ)": ("b", "V"), "m(tj)": ("t", "j"),
    "multilepton": None, "m(3j)": None, "m(multi)": None,
    "m(eejj)": None, "m(mumujj)": None,
    "m(ejj)": None, "m(mujj)": None, "m(taujj)": None, "m(gammajj)": None, "m(tbj)": None,
    "mT(ev)": None, "mT(muv)": None, "mT(taunu)": None,
}

SYM = {"e": "m(ee)", "mu": "m(mumu)", "tau": "m(tautau)", "j": "m(jj)", "b": "m(bb)",
       "t": "m(tt)", "ga": "m(gammagamma)", "V": "m(VV)", "H": "m(HH)"}
YKEY = {"e": "e", "mu": "m", "tau": "T", "j": "j", "b": "b", "t": "t", "ga": "g", "V": "V",
        "H": "H"}
GAP_WINDOW = (100.0, 5000.0)


@stage(
    name="two-body-matrix",
    group="budget",
    summary="every pair of grid objects: scanned or not, and what the gap would cost",
    outputs=["tex/two_body_matrix.tex", "tables/two_body_matrix.csv"],
    needs=["tables/census_budget.csv"],
)
def main(options=None):
    by_obs = models_by_spectrum()
    order = canonical_order(by_obs)

    published = {r["budget_axis"] for r in io.read_rows(paths.table("census_budget.csv"))
                 if r["budget_axis"] != "-" and float(r["n_s"]) > 0}

    missing = [o for o in order if o not in PAIR]
    if missing:
        raise SystemExit(f"no object pair classified for {missing}; extend PAIR")
    stale = [o for o in PAIR if o not in order]
    if stale:
        raise SystemExit(f"PAIR names a spectrum that is not in the catalogue: {stale}")

    def cell(a, b):
        return tuple(sorted((a, b), key=KEYS.index))

    spent = collections.defaultdict(float)
    axes = collections.defaultdict(list)
    unscanned = collections.defaultdict(float)
    unscanned_axes = collections.defaultdict(list)
    for o in order:
        if PAIR[o] is None:
            continue
        c = cell(*PAIR[o])
        if o in published:
            spent[c] += ns_scan(o)
            axes[c].append(o)
        else:
            unscanned[c] += ns_scan(o)
            unscanned_axes[c].append(o)

    sigma = {k: 2.0 * res(SYM[k]) for k in KEYS}

    def gap_price(a, b):
        r = 0.5 * math.sqrt((sigma[a] ** 2 + sigma[b] ** 2) / 2.0)
        w = YM.weight(YKEY[a] + YKEY[b])
        _hi, ns, _ev, fits = YM.gate(*GAP_WINDOW, r, w)
        return ns if fits else 0.0

    cells = [cell(a, b) for i, a in enumerate(KEYS) for b in KEYS[i:]]
    gaps = [c for c in cells if c not in spent and c not in unscanned]
    unscanned_only = [c for c in cells if c in unscanned and c not in spent]
    thin = [c for c in gaps if gap_price(*c) == 0.0]
    gap_total = sum(gap_price(*c) for c in gaps)
    n_now = sum(ns_scan(o) for o in order)

    label = dict(OBJ)
    out = paths.tex("two_body_matrix.tex")
    io.ensure(out)
    with open(out, "w") as f:
        f.write("% Generated by searchbudget/stages/two_body_matrix.py. "
                "Do not edit: regenerate instead.\n")
        f.write("\\begin{tabular}{l" + "r" * len(KEYS) + "}\n\\toprule\n")
        f.write(" & " + " & ".join(label[k] for k in KEYS) + " \\\\\n\\midrule\n")
        for i, a in enumerate(KEYS):
            row = [label[a]]
            row += [""] * i
            for b in KEYS[i:]:
                c = cell(a, b)
                if c in spent and c in unscanned:
                    row.append(f"{spent[c]:.0f}\\,\\textit{{[{unscanned[c]:.0f}]}}")
                elif c in spent:
                    row.append(f"{spent[c]:.0f}")
                elif c in unscanned:
                    row.append(f"\\textit{{[{unscanned[c]:.0f}]}}")
                else:
                    p = gap_price(*c)
                    row.append(f"\\textit{{({p:.0f})}}" if p else "\\textit{(--)}")
            f.write(" & ".join(row) + " \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")

    table = []
    for c in cells:
        extra = [f"{unscanned[c]:.1f}" if c in unscanned else "0.0",
                 "; ".join(sorted(unscanned_axes[c]))]
        if c in spent:
            table.append([c[0], c[1], "scanned", f"{spent[c]:.1f}", len(axes[c]),
                          "; ".join(sorted(axes[c]))] + extra)
        elif c in unscanned:
            table.append([c[0], c[1], "axes unscanned", "0.0", 0, ""] + extra)
        else:
            p = gap_price(*c)
            table.append([c[0], c[1], "gap" if p else "gap, too thin to fit",
                          f"{p:.1f}", 0, ""] + extra)
    io.write_rows(paths.table("two_body_matrix.csv"),
                  ["object_1", "object_2", "status", "ns", "n_axes", "axes",
                   "ns_unscanned", "axes_unscanned"], table)

    print("wrote results/tex/two_body_matrix.tex, results/tables/two_body_matrix.csv")
    print(f"{len(cells)} pairs: {len(spent)} scanned, {len(unscanned_only)} priced in the budget "
          f"with no published search, {len(gaps)} with no axis in the catalogue, "
          f"of which {len(thin)} cannot hold a fittable histogram")
    print("unscanned axes: " + "; ".join(
        f"{'-'.join(c)}: {', '.join(sorted(unscanned_axes[c]))} ({unscanned[c]:.0f} looks)"
        for c in cells if c in unscanned))
    print(f"gaps: {sorted('-'.join(c) for c in gaps)}")
    print(f"too thin: {sorted('-'.join(c) for c in thin)}")
    print(f"closing every gap: N {n_now:,.0f} -> {n_now + gap_total:,.0f} "
          f"(+{gap_total:,.0f}), Z {z5(n_now):.2f} -> {z5(n_now + gap_total):.2f}")
